import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>{/* 必要に応じて追加のmetaタグやfaviconを設定 */}</head>
      <body style={{ margin: 0, padding: 0, fontFamily: "Arial, sans-serif" }}>
        <header
          style={{
            backgroundColor: "#1976d2",
            color: "#fff",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <h1>TODOアプリ</h1>
        </header>
        <main style={{ padding: "1rem" }}>{children}</main>
        <footer
          style={{
            marginTop: "2rem",
            padding: "1rem",
            backgroundColor: "#f5f5f5",
            textAlign: "center",
          }}
        >
          © 2024 TODO App
        </footer>
      </body>
    </html>
  );
}
