import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { Container } from "@mui/material";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body style={{ margin: 0, padding: 0, fontFamily: "Arial, sans-serif" }}>
        <Header />
        <Container component="main" sx={{ padding: "2rem 0" }}>
          {children}
        </Container>
        <footer
          style={{
            marginTop: "2rem",
            padding: "1rem",
            backgroundColor: "#f5f5f5",
            textAlign: "center",
          }}
        >
          © 2024 Todo App
        </footer>
      </body>
    </html>
  );
}
